eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/reviews-db?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false

management:
  zipkin:
    tracing:
      enabled: true
      endpoint: http://zipkin:9411/api/v2/spans